CAREGIVERS = [
    {
        "id": "cg-001",
        "name": "Maria Santos",
        "email": "maria.santos@email.com",
        "phone": "(415) 555-0101",
        "photo_url": "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
        "bio": "Compassionate CNA with 12 years of experience specializing in dementia care. Bilingual in English and Spanish. Passionate about creating safe, comfortable environments for seniors.",
        "certifications": ["CNA", "CPR", "First Aid", "Dementia Care Specialist"],
        "specialties": ["dementia", "medication management", "companionship"],
        "hourly_rate": 32.00,
        "rating": 4.9,
        "total_reviews": 47,
        "years_experience": 12,
        "availability": {
            "monday": ["morning", "afternoon"],
            "tuesday": ["morning", "afternoon"],
            "wednesday": ["morning"],
            "thursday": ["morning", "afternoon"],
            "friday": ["morning", "afternoon"],
        },
        "background_check_status": "cleared",
        "languages": ["English", "Spanish"],
        "location": "San Francisco, CA",
        "joined_date": "2024-03-15",
        "total_bookings": 89,
        "is_active": True,
    },
    {
        "id": "cg-002",
        "name": "James Chen",
        "email": "james.chen@email.com",
        "phone": "(415) 555-0102",
        "photo_url": "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
        "bio": "Experienced HHA with expertise in mobility assistance and physical therapy support. Fluent in English and Cantonese. Known for patience and dedication to improving quality of life.",
        "certifications": ["HHA", "CPR", "First Aid"],
        "specialties": ["mobility", "personal hygiene", "meal prep"],
        "hourly_rate": 28.00,
        "rating": 4.7,
        "total_reviews": 35,
        "years_experience": 8,
        "availability": {
            "monday": ["morning", "afternoon", "evening"],
            "tuesday": ["morning", "afternoon"],
            "wednesday": ["morning", "afternoon", "evening"],
            "thursday": ["morning", "afternoon"],
            "friday": ["morning"],
        },
        "background_check_status": "cleared",
        "languages": ["English", "Cantonese"],
        "location": "Oakland, CA",
        "joined_date": "2024-06-20",
        "total_bookings": 62,
        "is_active": True,
    },
    {
        "id": "cg-003",
        "name": "Priya Patel",
        "email": "priya.patel@email.com",
        "phone": "(415) 555-0103",
        "photo_url": "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
        "bio": "Dedicated caregiver with a nursing background. Specializes in post-operative care and medication management. Creates personalized care plans for each client.",
        "certifications": ["CNA", "HHA", "CPR", "First Aid", "Medication Administration"],
        "specialties": ["medication management", "companionship", "meal prep"],
        "hourly_rate": 35.00,
        "rating": 4.8,
        "total_reviews": 52,
        "years_experience": 15,
        "availability": {
            "monday": ["morning", "afternoon"],
            "tuesday": ["morning", "afternoon"],
            "wednesday": ["morning", "afternoon"],
            "thursday": ["morning", "afternoon"],
            "friday": ["morning", "afternoon"],
        },
        "background_check_status": "cleared",
        "languages": ["English"],
        "location": "San Jose, CA",
        "joined_date": "2024-01-10",
        "total_bookings": 104,
        "is_active": True,
    },
    {
        "id": "cg-004",
        "name": "Rosa Gutierrez",
        "email": "rosa.gutierrez@email.com",
        "phone": "(415) 555-0104",
        "photo_url": "https://api.dicebear.com/7.x/avataaars/svg?seed=Rosa",
        "bio": "Warm and reliable caregiver with strong focus on companionship and emotional wellbeing. Expert in meal preparation for special dietary needs. Bilingual English/Spanish.",
        "certifications": ["HHA", "CPR", "First Aid"],
        "specialties": ["companionship", "meal prep", "medication management"],
        "hourly_rate": 25.00,
        "rating": 4.6,
        "total_reviews": 28,
        "years_experience": 5,
        "availability": {
            "monday": ["afternoon", "evening"],
            "tuesday": ["afternoon", "evening"],
            "wednesday": ["afternoon", "evening"],
            "thursday": ["afternoon", "evening"],
            "friday": ["afternoon"],
            "saturday": ["morning", "afternoon"],
        },
        "background_check_status": "cleared",
        "languages": ["English", "Spanish"],
        "location": "Daly City, CA",
        "joined_date": "2025-02-01",
        "total_bookings": 31,
        "is_active": True,
    },
    {
        "id": "cg-005",
        "name": "David Kim",
        "email": "david.kim@email.com",
        "phone": "(415) 555-0105",
        "photo_url": "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
        "bio": "Former physical therapy assistant turned home health aide. Skilled in mobility exercises and fall prevention. Patient and encouraging with all clients.",
        "certifications": ["CNA", "CPR", "First Aid"],
        "specialties": ["mobility", "personal hygiene", "companionship"],
        "hourly_rate": 30.00,
        "rating": 4.5,
        "total_reviews": 22,
        "years_experience": 6,
        "availability": {
            "monday": ["morning", "afternoon"],
            "wednesday": ["morning", "afternoon"],
            "friday": ["morning", "afternoon"],
            "saturday": ["morning"],
            "sunday": ["morning"],
        },
        "background_check_status": "cleared",
        "languages": ["English"],
        "location": "Berkeley, CA",
        "joined_date": "2025-01-15",
        "total_bookings": 38,
        "is_active": True,
    },
    {
        "id": "cg-006",
        "name": "Elena Reyes",
        "email": "elena.reyes@email.com",
        "phone": "(415) 555-0106",
        "photo_url": "https://api.dicebear.com/7.x/avataaars/svg?seed=Elena",
        "bio": "Certified nursing assistant with a heart for dementia and Alzheimer's care. Known for creative engagement activities and gentle redirection techniques.",
        "certifications": ["CNA", "HHA", "CPR", "First Aid", "Alzheimer's Care"],
        "specialties": ["dementia", "companionship", "medication management"],
        "hourly_rate": 33.00,
        "rating": 4.8,
        "total_reviews": 41,
        "years_experience": 10,
        "availability": {
            "monday": ["morning", "afternoon"],
            "tuesday": ["morning", "afternoon"],
            "wednesday": ["morning"],
            "thursday": ["morning", "afternoon"],
            "friday": ["morning", "afternoon"],
            "saturday": ["morning"],
        },
        "background_check_status": "cleared",
        "languages": ["English", "Tagalog"],
        "location": "San Francisco, CA",
        "joined_date": "2024-08-05",
        "total_bookings": 73,
        "is_active": True,
    },
    {
        "id": "cg-007",
        "name": "Michael Thompson",
        "email": "michael.t@email.com",
        "phone": "(415) 555-0107",
        "photo_url": "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
        "bio": "Experienced caregiver specializing in mobility assistance and transportation. Strong background in emergency response. Dependable and punctual.",
        "certifications": ["HHA", "CPR", "First Aid"],
        "specialties": ["mobility", "companionship", "meal prep"],
        "hourly_rate": 27.00,
        "rating": 4.4,
        "total_reviews": 19,
        "years_experience": 4,
        "availability": {
            "tuesday": ["morning", "afternoon", "evening"],
            "wednesday": ["morning", "afternoon", "evening"],
            "thursday": ["morning", "afternoon"],
            "friday": ["morning", "afternoon", "evening"],
            "saturday": ["morning", "afternoon"],
        },
        "background_check_status": "cleared",
        "languages": ["English"],
        "location": "Hayward, CA",
        "joined_date": "2025-04-10",
        "total_bookings": 21,
        "is_active": True,
    },
    {
        "id": "cg-008",
        "name": "Linda Nguyen",
        "email": "linda.nguyen@email.com",
        "phone": "(415) 555-0108",
        "photo_url": "https://api.dicebear.com/7.x/avataaars/svg?seed=Linda",
        "bio": "Detail-oriented caregiver with expertise in medication management and chronic disease support. Creates organized care schedules and keeps meticulous health logs.",
        "certifications": ["CNA", "CPR", "First Aid", "Medication Administration"],
        "specialties": ["medication management", "personal hygiene", "companionship"],
        "hourly_rate": 29.00,
        "rating": 4.7,
        "total_reviews": 33,
        "years_experience": 7,
        "availability": {
            "monday": ["morning", "afternoon"],
            "tuesday": ["morning", "afternoon"],
            "wednesday": ["morning", "afternoon"],
            "thursday": ["morning"],
            "friday": ["morning", "afternoon"],
        },
        "background_check_status": "cleared",
        "languages": ["English"],
        "location": "Fremont, CA",
        "joined_date": "2024-11-20",
        "total_bookings": 45,
        "is_active": True,
    },
    {
        "id": "cg-009",
        "name": "Carlos Mendez",
        "email": "carlos.mendez@email.com",
        "phone": "(415) 555-0109",
        "photo_url": "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
        "bio": "Energetic and caring aide with a focus on active aging. Encourages light exercise, social engagement, and nutritious eating. Fluent in Spanish and English.",
        "certifications": ["HHA", "CPR", "First Aid"],
        "specialties": ["companionship", "meal prep", "mobility"],
        "hourly_rate": 24.00,
        "rating": 4.3,
        "total_reviews": 15,
        "years_experience": 3,
        "availability": {
            "monday": ["afternoon", "evening"],
            "tuesday": ["morning", "afternoon"],
            "wednesday": ["afternoon", "evening"],
            "thursday": ["morning", "afternoon", "evening"],
            "friday": ["afternoon"],
            "saturday": ["morning", "afternoon"],
            "sunday": ["morning"],
        },
        "background_check_status": "cleared",
        "languages": ["English", "Spanish"],
        "location": "San Mateo, CA",
        "joined_date": "2025-06-01",
        "total_bookings": 17,
        "is_active": True,
    },
    {
        "id": "cg-010",
        "name": "Susan Walsh",
        "email": "susan.walsh@email.com",
        "phone": "(415) 555-0110",
        "photo_url": "https://api.dicebear.com/7.x/avataaars/svg?seed=Susan",
        "bio": "Retired registered nurse providing premium home care. Extensive medical knowledge combined with genuine compassion. Specializes in complex care needs.",
        "certifications": ["CNA", "HHA", "CPR", "First Aid", "Dementia Care Specialist", "Medication Administration"],
        "specialties": ["dementia", "medication management", "personal hygiene", "mobility"],
        "hourly_rate": 35.00,
        "rating": 4.9,
        "total_reviews": 58,
        "years_experience": 15,
        "availability": {
            "monday": ["morning", "afternoon"],
            "tuesday": ["morning", "afternoon"],
            "wednesday": ["morning", "afternoon"],
            "thursday": ["morning", "afternoon"],
            "friday": ["morning"],
        },
        "background_check_status": "cleared",
        "languages": ["English"],
        "location": "Palo Alto, CA",
        "joined_date": "2024-02-28",
        "total_bookings": 112,
        "is_active": True,
    },
]


FAMILIES = [
    {
        "id": "fm-001",
        "name": "The Johnson Family",
        "email": "johnson.family@email.com",
        "phone": "(415) 555-0201",
        "location": "San Francisco, CA",
        "care_recipient": {
            "name": "Dorothy Johnson",
            "age": 82,
            "care_needs": ["companionship", "medication reminders", "meal preparation"],
            "medical_conditions": ["mild dementia", "hypertension"],
            "mobility_level": "assisted",
            "notes": "Loves gardening and old movies. Needs gentle reminders for meals.",
        },
        "preferred_schedule": {
            "monday": ["morning", "afternoon"],
            "wednesday": ["morning", "afternoon"],
            "friday": ["morning", "afternoon"],
        },
        "budget_min": 25.00,
        "budget_max": 35.00,
        "joined_date": "2024-04-10",
        "total_bookings": 12,
        "is_active": True,
    },
    {
        "id": "fm-002",
        "name": "The Chen Family",
        "email": "chen.family@email.com",
        "phone": "(415) 555-0202",
        "location": "Oakland, CA",
        "care_recipient": {
            "name": "Wei Chen",
            "age": 88,
            "care_needs": ["personal hygiene", "mobility assistance", "medication reminders"],
            "medical_conditions": ["arthritis", "diabetes type 2"],
            "mobility_level": "wheelchair",
            "notes": "Prefers Cantonese-speaking caregiver. Needs help with daily exercises.",
        },
        "preferred_schedule": {
            "monday": ["morning", "afternoon"],
            "tuesday": ["morning", "afternoon"],
            "wednesday": ["morning", "afternoon"],
            "thursday": ["morning", "afternoon"],
            "friday": ["morning", "afternoon"],
        },
        "budget_min": 28.00,
        "budget_max": 35.00,
        "joined_date": "2024-05-22",
        "total_bookings": 18,
        "is_active": True,
    },
    {
        "id": "fm-003",
        "name": "The Martinez Family",
        "email": "martinez.family@email.com",
        "phone": "(415) 555-0203",
        "location": "San Jose, CA",
        "care_recipient": {
            "name": "Carmen Martinez",
            "age": 76,
            "care_needs": ["companionship", "light housekeeping", "transportation"],
            "medical_conditions": ["recovering from hip surgery"],
            "mobility_level": "assisted",
            "notes": "Spanish-speaking preferred. Temporary care during recovery period.",
        },
        "preferred_schedule": {
            "monday": ["afternoon"],
            "wednesday": ["afternoon"],
            "friday": ["afternoon"],
        },
        "budget_min": 22.00,
        "budget_max": 30.00,
        "joined_date": "2025-01-15",
        "total_bookings": 6,
        "is_active": True,
    },
    {
        "id": "fm-004",
        "name": "The Patel Family",
        "email": "patel.family@email.com",
        "phone": "(415) 555-0204",
        "location": "Fremont, CA",
        "care_recipient": {
            "name": "Raj Patel",
            "age": 91,
            "care_needs": ["medication reminders", "meal preparation", "personal hygiene", "companionship"],
            "medical_conditions": ["Parkinson's disease", "mild cognitive impairment"],
            "mobility_level": "assisted",
            "notes": "Needs patient, calm caregiver. Enjoys chess and reading.",
        },
        "preferred_schedule": {
            "monday": ["morning", "afternoon"],
            "tuesday": ["morning", "afternoon"],
            "wednesday": ["morning", "afternoon"],
            "thursday": ["morning", "afternoon"],
            "friday": ["morning", "afternoon"],
            "saturday": ["morning"],
        },
        "budget_min": 30.00,
        "budget_max": 38.00,
        "joined_date": "2024-07-08",
        "total_bookings": 22,
        "is_active": True,
    },
    {
        "id": "fm-005",
        "name": "The O'Brien Family",
        "email": "obrien.family@email.com",
        "phone": "(415) 555-0205",
        "location": "Daly City, CA",
        "care_recipient": {
            "name": "Margaret O'Brien",
            "age": 85,
            "care_needs": ["companionship", "meal preparation", "medication reminders"],
            "medical_conditions": ["congestive heart failure", "depression"],
            "mobility_level": "independent",
            "notes": "Lives alone. Needs social interaction and mood monitoring.",
        },
        "preferred_schedule": {
            "tuesday": ["morning", "afternoon"],
            "thursday": ["morning", "afternoon"],
            "saturday": ["morning"],
        },
        "budget_min": 24.00,
        "budget_max": 32.00,
        "joined_date": "2025-03-01",
        "total_bookings": 4,
        "is_active": True,
    },
    {
        "id": "fm-006",
        "name": "The Williams Family",
        "email": "williams.family@email.com",
        "phone": "(415) 555-0206",
        "location": "Berkeley, CA",
        "care_recipient": {
            "name": "Robert Williams",
            "age": 79,
            "care_needs": ["mobility assistance", "personal hygiene", "transportation"],
            "medical_conditions": ["stroke recovery", "limited left-side mobility"],
            "mobility_level": "assisted",
            "notes": "Needs help with physical therapy exercises. Very independent-minded.",
        },
        "preferred_schedule": {
            "monday": ["morning"],
            "wednesday": ["morning"],
            "friday": ["morning"],
        },
        "budget_min": 26.00,
        "budget_max": 34.00,
        "joined_date": "2024-09-14",
        "total_bookings": 15,
        "is_active": True,
    },
    {
        "id": "fm-007",
        "name": "The Tanaka Family",
        "email": "tanaka.family@email.com",
        "phone": "(415) 555-0207",
        "location": "San Mateo, CA",
        "care_recipient": {
            "name": "Keiko Tanaka",
            "age": 94,
            "care_needs": ["personal hygiene", "meal preparation", "companionship", "medication reminders"],
            "medical_conditions": ["advanced age", "osteoporosis", "vision impairment"],
            "mobility_level": "assisted",
            "notes": "Very gentle care needed. Falls risk. Enjoys origami and tea ceremony.",
        },
        "preferred_schedule": {
            "monday": ["morning", "afternoon"],
            "tuesday": ["morning", "afternoon"],
            "wednesday": ["morning", "afternoon"],
            "thursday": ["morning", "afternoon"],
            "friday": ["morning", "afternoon"],
        },
        "budget_min": 30.00,
        "budget_max": 40.00,
        "joined_date": "2024-06-30",
        "total_bookings": 20,
        "is_active": True,
    },
    {
        "id": "fm-008",
        "name": "The Rivera Family",
        "email": "rivera.family@email.com",
        "phone": "(415) 555-0208",
        "location": "San Francisco, CA",
        "care_recipient": {
            "name": "Luis Rivera",
            "age": 72,
            "care_needs": ["companionship", "light housekeeping", "meal preparation"],
            "medical_conditions": ["early-stage Alzheimer's"],
            "mobility_level": "independent",
            "notes": "Spanish-speaking preferred. Needs cognitive engagement activities.",
        },
        "preferred_schedule": {
            "monday": ["afternoon"],
            "wednesday": ["afternoon"],
            "friday": ["afternoon"],
            "saturday": ["morning"],
        },
        "budget_min": 22.00,
        "budget_max": 30.00,
        "joined_date": "2025-02-18",
        "total_bookings": 5,
        "is_active": True,
    },
]


BOOKINGS = [
    {
        "id": "bk-001",
        "caregiver_id": "cg-001",
        "caregiver_name": "Maria Santos",
        "family_id": "fm-001",
        "family_name": "The Johnson Family",
        "care_recipient_name": "Dorothy Johnson",
        "status": "completed",
        "start_date": "2026-01-06",
        "end_date": "2026-01-31",
        "hours_per_week": 18,
        "total_hours": 72,
        "hourly_rate": 32.00,
        "total_cost": 2304.00,
        "notes": "Regular care for Dorothy. Focus on companionship and medication reminders.",
        "created_at": "2025-12-28",
    },
    {
        "id": "bk-002",
        "caregiver_id": "cg-002",
        "caregiver_name": "James Chen",
        "family_id": "fm-002",
        "family_name": "The Chen Family",
        "care_recipient_name": "Wei Chen",
        "status": "completed",
        "start_date": "2026-01-06",
        "end_date": "2026-02-28",
        "hours_per_week": 25,
        "total_hours": 200,
        "hourly_rate": 28.00,
        "total_cost": 5600.00,
        "notes": "Full-time weekday care. Cantonese-speaking caregiver matched.",
        "created_at": "2025-12-20",
    },
    {
        "id": "bk-003",
        "caregiver_id": "cg-003",
        "caregiver_name": "Priya Patel",
        "family_id": "fm-004",
        "family_name": "The Patel Family",
        "care_recipient_name": "Raj Patel",
        "status": "in_progress",
        "start_date": "2026-03-01",
        "end_date": "2026-04-30",
        "hours_per_week": 30,
        "total_hours": 120,
        "hourly_rate": 35.00,
        "total_cost": 4200.00,
        "notes": "Specialized medication management and cognitive support.",
        "created_at": "2026-02-20",
    },
    {
        "id": "bk-004",
        "caregiver_id": "cg-004",
        "caregiver_name": "Rosa Gutierrez",
        "family_id": "fm-003",
        "family_name": "The Martinez Family",
        "care_recipient_name": "Carmen Martinez",
        "status": "in_progress",
        "start_date": "2026-03-10",
        "end_date": "2026-04-10",
        "hours_per_week": 12,
        "total_hours": 24,
        "hourly_rate": 25.00,
        "total_cost": 600.00,
        "notes": "Post-surgery recovery care. Spanish-speaking match.",
        "created_at": "2026-03-05",
    },
    {
        "id": "bk-005",
        "caregiver_id": "cg-005",
        "caregiver_name": "David Kim",
        "family_id": "fm-006",
        "family_name": "The Williams Family",
        "care_recipient_name": "Robert Williams",
        "status": "confirmed",
        "start_date": "2026-04-01",
        "end_date": "2026-05-31",
        "hours_per_week": 12,
        "total_hours": 96,
        "hourly_rate": 30.00,
        "total_cost": 2880.00,
        "notes": "Mobility-focused care with PT exercise support.",
        "created_at": "2026-03-20",
    },
    {
        "id": "bk-006",
        "caregiver_id": "cg-006",
        "caregiver_name": "Elena Reyes",
        "family_id": "fm-007",
        "family_name": "The Tanaka Family",
        "care_recipient_name": "Keiko Tanaka",
        "status": "in_progress",
        "start_date": "2026-02-15",
        "end_date": "2026-05-15",
        "hours_per_week": 25,
        "total_hours": 150,
        "hourly_rate": 33.00,
        "total_cost": 4950.00,
        "notes": "Gentle full-time care for advanced age needs.",
        "created_at": "2026-02-08",
    },
    {
        "id": "bk-007",
        "caregiver_id": "cg-001",
        "caregiver_name": "Maria Santos",
        "family_id": "fm-008",
        "family_name": "The Rivera Family",
        "care_recipient_name": "Luis Rivera",
        "status": "confirmed",
        "start_date": "2026-04-01",
        "end_date": "2026-06-30",
        "hours_per_week": 12,
        "total_hours": 144,
        "hourly_rate": 32.00,
        "total_cost": 4608.00,
        "notes": "Spanish-speaking dementia specialist for cognitive activities.",
        "created_at": "2026-03-22",
    },
    {
        "id": "bk-008",
        "caregiver_id": "cg-008",
        "caregiver_name": "Linda Nguyen",
        "family_id": "fm-004",
        "family_name": "The Patel Family",
        "care_recipient_name": "Raj Patel",
        "status": "completed",
        "start_date": "2025-12-01",
        "end_date": "2026-01-31",
        "hours_per_week": 20,
        "total_hours": 160,
        "hourly_rate": 29.00,
        "total_cost": 4640.00,
        "notes": "Medication management and daily care support.",
        "created_at": "2025-11-22",
    },
    {
        "id": "bk-009",
        "caregiver_id": "cg-010",
        "caregiver_name": "Susan Walsh",
        "family_id": "fm-007",
        "family_name": "The Tanaka Family",
        "care_recipient_name": "Keiko Tanaka",
        "status": "completed",
        "start_date": "2025-11-01",
        "end_date": "2026-01-31",
        "hours_per_week": 25,
        "total_hours": 300,
        "hourly_rate": 35.00,
        "total_cost": 10500.00,
        "notes": "Premium care with RN expertise for complex needs.",
        "created_at": "2025-10-25",
    },
    {
        "id": "bk-010",
        "caregiver_id": "cg-009",
        "caregiver_name": "Carlos Mendez",
        "family_id": "fm-005",
        "family_name": "The O'Brien Family",
        "care_recipient_name": "Margaret O'Brien",
        "status": "requested",
        "start_date": "2026-04-05",
        "end_date": "2026-05-05",
        "hours_per_week": 12,
        "total_hours": 48,
        "hourly_rate": 24.00,
        "total_cost": 1152.00,
        "notes": "Companionship-focused care for mood and social support.",
        "created_at": "2026-03-24",
    },
    {
        "id": "bk-011",
        "caregiver_id": "cg-007",
        "caregiver_name": "Michael Thompson",
        "family_id": "fm-006",
        "family_name": "The Williams Family",
        "care_recipient_name": "Robert Williams",
        "status": "completed",
        "start_date": "2026-01-15",
        "end_date": "2026-03-15",
        "hours_per_week": 12,
        "total_hours": 96,
        "hourly_rate": 27.00,
        "total_cost": 2592.00,
        "notes": "Mobility assistance and transportation services.",
        "created_at": "2026-01-08",
    },
    {
        "id": "bk-012",
        "caregiver_id": "cg-003",
        "caregiver_name": "Priya Patel",
        "family_id": "fm-001",
        "family_name": "The Johnson Family",
        "care_recipient_name": "Dorothy Johnson",
        "status": "completed",
        "start_date": "2025-10-01",
        "end_date": "2025-12-31",
        "hours_per_week": 18,
        "total_hours": 216,
        "hourly_rate": 35.00,
        "total_cost": 7560.00,
        "notes": "Long-term medication management and companionship.",
        "created_at": "2025-09-22",
    },
    {
        "id": "bk-013",
        "caregiver_id": "cg-006",
        "caregiver_name": "Elena Reyes",
        "family_id": "fm-001",
        "family_name": "The Johnson Family",
        "care_recipient_name": "Dorothy Johnson",
        "status": "confirmed",
        "start_date": "2026-04-01",
        "end_date": "2026-06-30",
        "hours_per_week": 18,
        "total_hours": 216,
        "hourly_rate": 33.00,
        "total_cost": 7128.00,
        "notes": "Dementia specialist care for Dorothy.",
        "created_at": "2026-03-25",
    },
    {
        "id": "bk-014",
        "caregiver_id": "cg-004",
        "caregiver_name": "Rosa Gutierrez",
        "family_id": "fm-008",
        "family_name": "The Rivera Family",
        "care_recipient_name": "Luis Rivera",
        "status": "cancelled",
        "start_date": "2026-02-01",
        "end_date": "2026-03-01",
        "hours_per_week": 12,
        "total_hours": 0,
        "hourly_rate": 25.00,
        "total_cost": 0,
        "notes": "Cancelled - family found temporary family help.",
        "created_at": "2026-01-25",
    },
    {
        "id": "bk-015",
        "caregiver_id": "cg-010",
        "caregiver_name": "Susan Walsh",
        "family_id": "fm-002",
        "family_name": "The Chen Family",
        "care_recipient_name": "Wei Chen",
        "status": "requested",
        "start_date": "2026-04-15",
        "end_date": "2026-07-15",
        "hours_per_week": 20,
        "total_hours": 240,
        "hourly_rate": 35.00,
        "total_cost": 8400.00,
        "notes": "Complex care needs requiring RN-level expertise.",
        "created_at": "2026-03-26",
    },
]


REVIEWS = [
    {
        "id": "rv-001",
        "booking_id": "bk-001",
        "caregiver_id": "cg-001",
        "caregiver_name": "Maria Santos",
        "family_id": "fm-001",
        "family_name": "The Johnson Family",
        "rating": 5,
        "comment": "Maria is absolutely wonderful with my mother. She has such patience with her memory issues and always keeps her engaged with activities. We feel so blessed to have found her.",
        "created_at": "2026-02-03",
    },
    {
        "id": "rv-002",
        "booking_id": "bk-002",
        "caregiver_id": "cg-002",
        "caregiver_name": "James Chen",
        "family_id": "fm-002",
        "family_name": "The Chen Family",
        "rating": 5,
        "comment": "James communicates beautifully with my father in Cantonese. His mobility exercises have noticeably improved Dad's range of motion. Highly recommend!",
        "created_at": "2026-03-05",
    },
    {
        "id": "rv-003",
        "booking_id": "bk-008",
        "caregiver_id": "cg-008",
        "caregiver_name": "Linda Nguyen",
        "family_id": "fm-004",
        "family_name": "The Patel Family",
        "rating": 5,
        "comment": "Linda's attention to Dad's medication schedule is incredible. She keeps detailed logs and always communicates with us about any changes she notices. True professional.",
        "created_at": "2026-02-05",
    },
    {
        "id": "rv-004",
        "booking_id": "bk-009",
        "caregiver_id": "cg-010",
        "caregiver_name": "Susan Walsh",
        "family_id": "fm-007",
        "family_name": "The Tanaka Family",
        "rating": 5,
        "comment": "Susan's nursing background gives us such peace of mind. She handles Mom's complex needs with expertise and genuine warmth. Worth every penny.",
        "created_at": "2026-02-10",
    },
    {
        "id": "rv-005",
        "booking_id": "bk-011",
        "caregiver_id": "cg-007",
        "caregiver_name": "Michael Thompson",
        "family_id": "fm-006",
        "family_name": "The Williams Family",
        "rating": 4,
        "comment": "Michael is reliable and good with Dad's mobility exercises. Would appreciate a bit more initiative with meal prep, but overall very satisfied.",
        "created_at": "2026-03-18",
    },
    {
        "id": "rv-006",
        "booking_id": "bk-012",
        "caregiver_id": "cg-003",
        "caregiver_name": "Priya Patel",
        "family_id": "fm-001",
        "family_name": "The Johnson Family",
        "rating": 5,
        "comment": "Priya created a beautiful care plan for Mom. Her medication management expertise is outstanding and she genuinely cares about her clients' wellbeing.",
        "created_at": "2026-01-05",
    },
    {
        "id": "rv-007",
        "booking_id": "bk-001",
        "caregiver_id": "cg-001",
        "caregiver_name": "Maria Santos",
        "family_id": "fm-001",
        "family_name": "The Johnson Family",
        "rating": 5,
        "comment": "Second time using Maria for Mom's care. She remembers all of Mom's preferences and routines. It's like having a family member help out.",
        "created_at": "2026-02-15",
    },
    {
        "id": "rv-008",
        "booking_id": "bk-002",
        "caregiver_id": "cg-002",
        "caregiver_name": "James Chen",
        "family_id": "fm-002",
        "family_name": "The Chen Family",
        "rating": 4,
        "comment": "Very good caregiver. Dad enjoys their conversations in Cantonese. Could be a bit more punctual in the mornings, but excellent care quality.",
        "created_at": "2026-03-01",
    },
    {
        "id": "rv-009",
        "booking_id": "bk-009",
        "caregiver_id": "cg-010",
        "caregiver_name": "Susan Walsh",
        "family_id": "fm-007",
        "family_name": "The Tanaka Family",
        "rating": 5,
        "comment": "Susan adapted her care approach perfectly to Mom's cultural preferences. She even learned some basic Japanese phrases. Exceptional caregiver.",
        "created_at": "2026-01-20",
    },
    {
        "id": "rv-010",
        "booking_id": "bk-012",
        "caregiver_id": "cg-003",
        "caregiver_name": "Priya Patel",
        "family_id": "fm-001",
        "family_name": "The Johnson Family",
        "rating": 5,
        "comment": "Priya went above and beyond during the holidays. She organized activities that kept Mom engaged and happy. Truly dedicated professional.",
        "created_at": "2025-12-28",
    },
    {
        "id": "rv-011",
        "booking_id": "bk-011",
        "caregiver_id": "cg-007",
        "caregiver_name": "Michael Thompson",
        "family_id": "fm-006",
        "family_name": "The Williams Family",
        "rating": 4,
        "comment": "Good care provider. Handles Dad's stubbornness with grace. Very helpful with transportation to appointments.",
        "created_at": "2026-02-20",
    },
    {
        "id": "rv-012",
        "booking_id": "bk-008",
        "caregiver_id": "cg-008",
        "caregiver_name": "Linda Nguyen",
        "family_id": "fm-004",
        "family_name": "The Patel Family",
        "rating": 5,
        "comment": "Linda noticed a medication interaction that even our pharmacy missed. Her vigilance and medical knowledge are remarkable. So grateful.",
        "created_at": "2026-01-15",
    },
]


PAYMENTS = [
    {
        "id": "pay-001",
        "booking_id": "bk-001",
        "family_id": "fm-001",
        "family_name": "The Johnson Family",
        "caregiver_id": "cg-001",
        "caregiver_name": "Maria Santos",
        "amount": 2304.00,
        "commission": 345.60,
        "net_payout": 1958.40,
        "status": "completed",
        "paid_at": "2026-02-05",
    },
    {
        "id": "pay-002",
        "booking_id": "bk-002",
        "family_id": "fm-002",
        "family_name": "The Chen Family",
        "caregiver_id": "cg-002",
        "caregiver_name": "James Chen",
        "amount": 5600.00,
        "commission": 840.00,
        "net_payout": 4760.00,
        "status": "completed",
        "paid_at": "2026-03-05",
    },
    {
        "id": "pay-003",
        "booking_id": "bk-008",
        "family_id": "fm-004",
        "family_name": "The Patel Family",
        "caregiver_id": "cg-008",
        "caregiver_name": "Linda Nguyen",
        "amount": 4640.00,
        "commission": 696.00,
        "net_payout": 3944.00,
        "status": "completed",
        "paid_at": "2026-02-08",
    },
    {
        "id": "pay-004",
        "booking_id": "bk-009",
        "family_id": "fm-007",
        "family_name": "The Tanaka Family",
        "caregiver_id": "cg-010",
        "caregiver_name": "Susan Walsh",
        "amount": 10500.00,
        "commission": 1575.00,
        "net_payout": 8925.00,
        "status": "completed",
        "paid_at": "2026-02-10",
    },
    {
        "id": "pay-005",
        "booking_id": "bk-011",
        "family_id": "fm-006",
        "family_name": "The Williams Family",
        "caregiver_id": "cg-007",
        "caregiver_name": "Michael Thompson",
        "amount": 2592.00,
        "commission": 388.80,
        "net_payout": 2203.20,
        "status": "completed",
        "paid_at": "2026-03-20",
    },
    {
        "id": "pay-006",
        "booking_id": "bk-012",
        "family_id": "fm-001",
        "family_name": "The Johnson Family",
        "caregiver_id": "cg-003",
        "caregiver_name": "Priya Patel",
        "amount": 7560.00,
        "commission": 1134.00,
        "net_payout": 6426.00,
        "status": "completed",
        "paid_at": "2026-01-08",
    },
    {
        "id": "pay-007",
        "booking_id": "bk-003",
        "family_id": "fm-004",
        "family_name": "The Patel Family",
        "caregiver_id": "cg-003",
        "caregiver_name": "Priya Patel",
        "amount": 4200.00,
        "commission": 630.00,
        "net_payout": 3570.00,
        "status": "pending",
        "paid_at": "2026-03-26",
    },
    {
        "id": "pay-008",
        "booking_id": "bk-006",
        "family_id": "fm-007",
        "family_name": "The Tanaka Family",
        "caregiver_id": "cg-006",
        "caregiver_name": "Elena Reyes",
        "amount": 4950.00,
        "commission": 742.50,
        "net_payout": 4207.50,
        "status": "pending",
        "paid_at": "2026-03-26",
    },
]
